server:
  port: 9090
spring:
  application:
    name: script-engine
  messages:
    encoding: UTF-8
    basename: messages
script:
  engine:
    outerJsRsList:
      - customFunc.js
      - lodash.js
logging:
  level:
    com.jcoder.script: debug